Chore: husky 브랜치명 룰 수정

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -35,8 +35,8 @@ if echo "$BRANCH_NAME" | grep -qE "(^[/\-])|([/\-]$)"; then
 fi
 
 # 커밋 메시지 Type 제한
-if ! echo "$BRANCH_NAME" | head -n 1 | grep -qE "^(bugfix|chore|config|develop|feature|hotfix|main|maintenance|qa|refactor|release)/"; then
-  echo -e "Branch name error: 허용되지 않은 브랜치명을 사용했습니다. \n허용된 브랜치명: bugfix, chore, config, develop, feature, hotfix, main, maintenance, qa, refactor, release"
+if ! echo "$BRANCH_NAME" | head -n 1 | grep -qE "^(bugfix|config|develop|feature|hotfix|main|maintenance|qa|refactor|release)/"; then
+  echo -e "Branch name error: 허용되지 않은 브랜치명을 사용했습니다. \n허용된 브랜치명: bugfix, config, develop, feature, hotfix, main, maintenance, qa, refactor, release"
   exit 1
 fi
 
